name: sumed
description: A SuMedchatbot.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  dialog_flowtter: ^0.3.3
  flutter_chat_ui: ^1.5.5
  modal_bottom_sheet: ^2.0.0
  get: ^4.6.1
#  awesome_select: ^5.1.0
  google_fonts: ^2.2.0
  intl: ^0.17.0
  direct_select_flutter: ^1.1.1
  numberpicker: ^2.1.1


#chat features
  file_picker: ^4.3.3
  image_picker: ^0.8.4+5
  mime: ^1.0.1
  open_file: ^3.2.1
  uuid: ^3.0.5

dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^1.0.4

flutter:
    uses-material-design: true
    assets:
      - assets/dialog_flow_auth.json
      - assets/images/



